apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manager.yaml
  - manager_config.yaml

patches:
  - path: controller_manager_config.yaml
    target:
      kind: ControllerManagerConfig
      name: manager-config
