apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-config
  namespace: mailer-operator-system
data:
  controller_manager_config.yaml: |
    # Add your manager configuration here
    # Example configuration:
    metrics:
      bind_address: "127.0.0.1:8080"
    health:
      bind_address: ":8081"
    leader_election:
      enabled: true
      lease_name: "b50c39f1.mailerlitetask.com"
