apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: email-viewer-role
rules:
- apiGroups:
  - email.mailerlitetask.com
  resources:
  - emails
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - email.mailerlitetask.com
  resources:
  - emails/status
  verbs:
  - get
