apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emailsenderconfig-editor-role
rules:
- apiGroups:
  - email.mailerlitetask.com
  resources:
  - emailsenderconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - email.mailerlitetask.com
  resources:
  - emailsenderconfigs/status
  verbs:
  - get
