apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth_proxy_client_clusterrole.yaml
  - auth_proxy_role.yaml
  - auth_proxy_role_binding.yaml
  - auth_proxy_service.yaml
  - email_editor_role.yaml
  - email_viewer_role.yaml
  - emailsenderconfig_editor_role.yaml
  - emailsenderconfig_viewer_role.yaml
  - leader_election_role.yaml
  - leader_election_role_binding.yaml
  - mailer-operator-cluster-role-binding.yaml
  - mailer-operator-cluster-role.yaml
  - role.yaml
  - role_binding.yaml
  - service_account.yaml
