apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: mailer-operator-system
rules:
- apiGroups:
  - email.mailerlitetask.com
  resources:
  - emails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - email.mailerlitetask.com
  resources:
  - emails/finalizers
  verbs:
  - update
- apiGroups:
  - email.mailerlitetask.com
  resources:
  - emails/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - email.mailerlitetask.com
  resources:
  - emailsenderconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - email.mailerlitetask.com
  resources:
  - emailsenderconfigs/status
  verbs:
  - get
  - patch
  - update
