apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
  namespace: mailer-operator-system
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: mailer-operator-system
roleRef:
  kind: Role
  name: manager-role
  apiGroup: rbac.authorization.k8s.io
