apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: controllermanagerconfigs.controller-runtime.sigs.k8s.io
  namespace: mailer-operator-system
spec:
  group: controller-runtime.sigs.k8s.io
  names:
    kind: ControllerManagerConfig
    listKind: ControllerManagerConfigList
    plural: controllermanagerconfigs
    singular: controllermanagerconfig
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                metrics:
                  type: object
                  properties:
                    bindAddress:
                      type: string
                health:
                  type: object
                  properties:
                    healthProbeBindAddress:
                      type: string
                webhook:
                  type: object
                  properties:
                    port:
                      type: integer
                leaderElection:
                  type: object
                  properties:
                    leaderElect:
                      type: boolean
                    resourceName:
                      type: string
