apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: emailsenderconfigs.email.mailerlitetask.com
spec:
  group: email.mailerlitetask.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                apiTokenSecretRef:
                  type: string
                senderEmail:
                  type: string
            status:
              type: object
              properties:
                error:
                  type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: emailsenderconfigs
    singular: emailsenderconfig
    kind: EmailSenderConfig
    shortNames:
    - esc
